#define USER_WANT_TO_INSERT 1
#define USER_WANT_TO_DISPLAY 2
#define USER_WANT_TO_DELETE_NODE 3
#define USER_WANT_TO_DELETE_WHOLE_LIST 4
#define USER_WANT_TO_Print_LIST_REVERSE 5
#define USER_WANT_TO_EXIT 6

